spring:
  datasource:
    url: jdbc:postgresql://kassa-app-db:5432/omoda-db
    username: rob
    password: wendy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false

server:
  port: 8080