spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:kassa-app-db}:${DB_PORT:5432}/${DB_NAME:omoda-db}
    username: ${DB_USER:rob}
    password: ${DB_PASSWORD:wendy}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false

server:
  port: 8080